name: Prek auto-update

on:
  # every month
  schedule:
    - cron: "0 0 1 * *"
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - run: pip install prek

      - run: prek auto-update

      - uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/prek-hooks
          title: Update prek hooks
          commit-message: "chore: update prek hooks"
          body: Update versions of prek-managed hooks to latest version.
